version: '3.9'

services:

  php:
    build: ./php
    restart: always
    ports:
     - 8081:80
    
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 25A27z13c0706
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root 
      - PMA_PASSWORD=25A27z13c0706
    volumes:
      - ./data/mysql:/var/lib/mysql
    

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d